# Traefik dynamic configuration
# Defines shared middlewares

http:
  middlewares:
    sitey-redirect-https:
      redirectScheme:
        scheme: https
        permanent: true

    sitey-compress:
      compress: {}
